name: Deploy kitshn.app
on:
  push:
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./web
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kitshn-app
          directory: web/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}